version: '3'

services:
  dev-box:
    build:
      context: ../..
      dockerfile: ./build/docker/Dockerfile.truffle
    working_dir: /src/      
    volumes:
      - ../../src/contracts/:/src/contracts
      - ../../deployments/contracts:/src/
      - dev-build:/build
    tty: true
    stdin_open: true
    command: 
      - /bin/sh
      - -c
      - |
        truffle compile --contracts_directory ./migration_contract --contracts_build_directory /build --network development;
        truffle migrate --contracts_build_directory /build --network development;
volumes:
  dev-build:
