#!/usr/bin/env python3

import argparse
import os
import subprocess
import sys


def make_parser():
    parser = argparse.ArgumentParser(
        description=
        """
        CDIP dev environment
        """,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    subparser = parser.add_subparsers(help="command",  dest="command")

    dev_parser = subparser.add_parser("dev",
                                      help="migrate locally")
    dev_parser.add_argument("-c", "--console", action="store_true",
                            help="launch truffle development console")
    dev_parser.add_argument("-s", "--shell", action="store_true",
                            help="attach to truffle box shell")
    dev_parser.add_argument("-b", "--build", action="store_true",
                            help="rebuild docker containers")

    return(parser)


if __name__ == '__main__':

    if sys.version_info<(3,0,0):
        sys.stderr.write("You need python 3.0 or later to run this script\n")
        sys.exit(1)

    abspath = os.path.abspath(__file__)
    dname = os.path.dirname(abspath)
    os.chdir(dname)

    try:
        p = make_parser()
        args = p.parse_args()

        if args.command == "dev":
            run = ["docker-compose",
                   "-p", "cdip", "--env-file", "../deployments/dev/dev.env",
                   "-f", "../deployments/dev/docker-compose.ganache.yml",
                   "-f", "../deployments/dev/docker-compose.truffle.yml",
                   "-f", "../deployments/dev/docker-compose.server.yml",
                   "-f", "../deployments/web/docker-compose.server.yml",
                   "up", "-d"]
            if args.build:
                run += ["--build"]
            subprocess.call(run)
            if args.console:
                print("launching truffle console")
                subprocess.call(["docker", "exec", "-it", "cdip_truffle-box_1",
                                 "/scripts/truffle-launch-console.sh"])
            elif args.shell:
                subprocess.call(["docker", "exec", "-it", "cdip_truffle-box_1", "/bin/sh"])
                print("done")
        else:
            raise Exception()
    except Exception:
        p.print_help()
