#!/usr/bin/env python3

import argparse
import os
import subprocess
import sys


def make_parser():
    parser = argparse.ArgumentParser(
        description=
        """
        CDIP dev environment
        """,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    subparser = parser.add_subparsers(help="command",  dest="command")

    dev_parser = subparser.add_parser("dev",
                                      help="migrate locally")
    dev_parser.add_argument("-c", "--console", action="store_true",
                            help="launch truffle development console")
    dev_parser.add_argument("-s", "--shell", action="store_true",
                            help="attach to truffle box shell")
    dev_parser.add_argument("-b", "--build", action="store_true",
                            help="rebuild docker containers")

    return(parser)


if __name__ == '__main__':

    if sys.version_info<(3,0,0):
        sys.stderr.write("You need python 3.0 or later to run this script\n")
        sys.exit(1)

    abspath = os.path.abspath(__file__)
    dname = os.path.dirname(abspath)
    os.chdir(dname)

    try:
        p = make_parser()
        args = p.parse_args()

        if args.command == "dev":
            run_ganache = ["docker-compose",
                           "-p", "cdip",
                           "--env-file", "../deployments/dev/dev.env",
                           "-f", "../deployments/dev/docker-compose.ganache.yml",
                           "up", "-d"]
            if args.build:
                run_ganache += ["--build"]
            subprocess.call(run_ganache)

            if args.build:
                build_truffle = ["docker-compose",
                                 "-p", "cdip",
                                 "-f", "../deployments/dev/docker-compose.truffle.yml",
                                 "build", "--no-cache"]
                build_web = ["docker-compose",
                             "-p", "cdip",
                             "-f", "../deployments/web/docker-compose.server.yml",
                             "build", "--no-cache"]
                subprocess.call(build_truffle)
                subprocess.call(build_web)

            run_truffle = ["docker-compose",
                           "-p", "cdip",
                           "--env-file", "../deployments/dev/dev.env",
                           "-f", "../deployments/dev/docker-compose.truffle.yml",
                           "run",
                           "--rm",
                           "truffle-box"]

            run_web = ["docker-compose",
                       "-p", "cdip",
                       "--env-file", "../deployments/dev/dev.env",
                       "-f", "../deployments/dev/docker-compose.server.yml",
                       "-f", "../deployments/web/docker-compose.server.yml",
                       "up", "-d"]

            if args.console:
                run_truffle += ["/scripts/truffle-launch-console.sh"]
            elif args.shell:
                run_truffle += ["/bin/sh"]
            subprocess.call(run_web)
            subprocess.call(run_truffle)
        else:
            raise Exception()
    except Exception:
        p.print_help()
